spring:
  application:
    name: seminar
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/bts3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5044323#Ee
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
